package assignment.service;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import assignment.model.Order;
import assignment.model.Order.OrderStatus;
import assignment.repository.OrderRepository;
import assignment.repository.ProductRepository;

@Service
public class OrderService {

    private final OrderRepository orderRepository;
    private final ProductRepository productRepository;

    public OrderService(ProductRepository productRepository, OrderRepository orderRepository) {
        this.productRepository = productRepository;
        this.orderRepository = orderRepository;
        }
    
    // Creates a new order
    public Order placeOrder(int customerID, String productID, int orderQuantity) {

        // makes sure quantity is more than 0
        if (orderQuantity <= 0) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Quantity must be greater than 0.");
        }

        // Check if the product exists
        productRepository.findById(productID).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Product not found: " + productID));

        // Create new Order object
        Order order = new Order(customerID, productID, orderQuantity);
        return orderRepository.save(order);
    }

    public List<Order> getAllOrders() {
        return orderRepository.findAll();
    }

    public List<Order> getOrdersByCustomerID(int customerID) {
        return orderRepository.findOrdersByCustomerID(customerID);
    }

    // Cancel Order
    public void cancelOrder(int customerID, int orderID) {
        Order order = orderRepository.findById(orderID).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Order not found: " + orderID));

        // Check if the customer owns the order
        if (order.getCustomerID() != customerID) {
            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "The order was not cancelled as this order does not belong to you.");
        }

        // Check if order has already been shipped
        if (order.getStatus() != OrderStatus.NOT_SHIPPED) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Cannot cancel order that has already been shipped. ");
        }

        // Delete the order
        orderRepository.delete(order);
    }

    public Order updateOrderStatus(int orderID, OrderStatus newStatus) {
        Order order = orderRepository.findById(orderID).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Order not found: " + orderID));
        order.setStatus(newStatus);
        return orderRepository.save(order);
    }

    public double getCustomerRevenue(int customerID) {
        Double total = orderRepository.getTotalRevenueByCustomer(customerID);
        return total != null ? total : 0.0; // handles null by returning 0.0 if customer has no shipped orders (this was generated by AI)
    }
}